import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "../components/NavBar"
import Sidebar from '../components/sidebar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FeaturesPage({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true} // that stupid hydration error, it will go away with this
      >
        
        <div className="flex h-screen">
          <Sidebar />
          <div className="flex-1 flex flex-col">
            <div className="flex justify-end pt-[1%] pr-[2%]">
              <NavBar />
            </div>
            <main className="mt-[2%] px-[4%] flex-1 overflow-auto">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
