"use client";

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

export default function AboutPage() {
  const router = useRouter();
  
  return (
    <div className="min-h-screen bg-[#09090B] text-white">
      {/* Navigation */}
      <header className="bg-[#09090B] w-[100%] h-[70px] flex justify-between items-center px-[40px] border-b border-solid border-[#E3DEED] sticky top-0 z-50">
        <div className="flex h-[100%] items-center cursor-pointer" onClick={() => router.push('/')}>
          <Image src="/Assets/quiver-logo.svg" alt='Quiver' width={50} height={50} className="mr-[10px]" />
          <p className="text-[28px]">Quiver</p>
        </div>
        <div className="flex items-center space-x-8">
          <Link href="/" className="text-[#635C70] hover:text-white transition-colors">Home</Link>
          <Link href="/contact" className="text-[#635C70] hover:text-white transition-colors">Contact</Link>
          <Link href="/privacy" className="text-[#635C70] hover:text-white transition-colors">Privacy</Link>
          <button 
            onClick={() => router.push('/signin')}
            className="px-5 py-2 rounded-md text-white bg-[#5222D0] flex items-center justify-center tracking-wider transition-all duration-300 hover:shadow-[0_0_15px_rgba(82,34,208,0.5)] hover:scale-105"
          >
            Sign In
          </button>
        </div>
      </header>

      {/* Hero Section */}
      <div className="relative bg-gradient-to-b from-[#09090B] to-[#131218] py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center">
            <h1 className="text-5xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-[#5222D0] via-[#9B87F5] to-[#5222D0] bg-clip-text text-transparent bg-size-200 animate-gradient-x">About Quiver</h1>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              Reimagining how students learn in the AI era
            </p>
          </div>
        </div>
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute -top-40 -right-40 w-80 h-80 bg-[#5222D0] rounded-full opacity-10 blur-3xl"></div>
          <div className="absolute top-60 -left-20 w-60 h-60 bg-[#EC615B] rounded-full opacity-10 blur-3xl"></div>
        </div>
      </div>

      {/* Our Story */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
          <div>
            <h2 className="text-3xl font-bold mb-6 text-[#9B87F5]">Our Story</h2>
            <p className="text-gray-300 mb-6">
              Quiver was born from a simple observation: despite the digital revolution, ehhh, who am I kidding, ITS TO GET MARKS IN UNI BRO.
            </p>
            <p className="text-gray-300 mb-6">
              Founded in 2023 by a team of education specialists and AI engineers, our mission is to harness the power of artificial intelligence to create more effective, personalized learning experiences...and yes that entire text was generated by GPT because I'm not creative enough to write an about us page ok?
            </p>
            <p className="text-gray-300">
              We believe the future of education isn't just about consuming information (its already doomed), but about interacting with it in ways that align with how our brains actually learn and remember (do they even learn?).
            </p>
          </div>
          <div className="relative">
            <div className="absolute inset-0 bg-gradient-to-tr from-[#5222D0] to-transparent opacity-20 rounded-lg transform rotate-3"></div>
            <Image 
              src="/Assets/landingPage/landingPage.svg" 
              alt="Quiver team" 
              width={600} 
              height={400}
              className="rounded-lg relative z-10 shadow-xl"
            />
          </div>
        </div>
      </section>

      {/* Our Mission */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-[#131218]">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-4 text-[#9B87F5]">Our Mission</h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              To transform how students learn by providing AI-powered tools that adapt to individual learning styles and needs.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
            <div className="bg-[#1A1830] p-8 rounded-lg border border-[#3A3151] transition-all duration-300 hover:transform hover:scale-105 hover:shadow-[0_5px_30px_rgba(82,34,208,0.2)]">
              <div className="bg-[#27272A] w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-[#9B87F5]">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-3 text-white">Innovate</h3>
              <p className="text-gray-400">
                Continually pushing the boundaries of educational technology to create more effective learning experiences.
              </p>
            </div>
            
            <div className="bg-[#1A1830] p-8 rounded-lg border border-[#3A3151] transition-all duration-300 hover:transform hover:scale-105 hover:shadow-[0_5px_30px_rgba(82,34,208,0.2)]">
              <div className="bg-[#27272A] w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-[#9B87F5]">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-3 text-white">Empower</h3>
              <p className="text-gray-400">
                Giving students the tools to take control of their learning journey and achieve their academic goals.
              </p>
            </div>
            
            <div className="bg-[#1A1830] p-8 rounded-lg border border-[#3A3151] transition-all duration-300 hover:transform hover:scale-105 hover:shadow-[0_5px_30px_rgba(82,34,208,0.2)]">
              <div className="bg-[#27272A] w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-[#9B87F5]">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              </div>
              <h3 className="text-xl font-semibold mb-3 text-white">Accelerate</h3>
              <p className="text-gray-400">
                Supercharging learning efficiency so students can achieve more in less time with better retention.
              </p>
            </div>
          </div>
        </div>
      </section>




      {/* CTA Section */}
      <section className="py-16 px-4 bg-gradient-to-r from-[#1A1830] to-[#27272A] relative overflow-hidden">
        <div className="max-w-7xl mx-auto relative z-10">
          <div className="text-center">
            <h2 className="text-3xl font-bold mb-6 text-white">Ready to transform your learning experience?</h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto mb-8">
              Join thousands of students already using Quiver to study smarter, not harder.
            </p>
            <button 
              onClick={() => router.push('/signup')}
              className="px-8 py-4 bg-[#5222D0] text-white rounded-lg text-lg font-medium hover:bg-[#4319B3] transition-all hover:shadow-[0_0_30px_rgba(82,34,208,0.5)] hover:scale-105"
            >
              Get Started Free
            </button>
          </div>
        </div>
        <div className="absolute top-0 left-0 w-full h-full">
          <div className="absolute top-10 left-10 w-40 h-40 bg-[#5222D0] rounded-full blur-3xl opacity-10"></div>
          <div className="absolute bottom-10 right-10 w-60 h-60 bg-[#5222D0] rounded-full blur-3xl opacity-10"></div>
        </div>
      </section>

    </div>
  );
}