import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "../components/NavBar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardPage({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true} // that stupid hydration error, it will go away with this
      >
        <div className="flex justify-end">
        <NavBar></NavBar>
        </div>
        <p>Hellooooooo</p>
        {children}
      </body>
    </html>
  );
}
