import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "../components/navBar"
import Sidebar from '../components/sidebar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardPage({ children }) {
  return (
        <div className="flex min-h-screen bg-[#09090B]">
          <Sidebar />
          <div className="flex-1 flex flex-col bg-[#09090B]">
            <div className="flex justify-end pt-[1%] pr-[2%] bg-[#09090B] sticky top-0 z-10 right-0">
              <NavBar />
            </div>
            <main className="px-[4%] bg-[#09090B]">{children}</main>
          </div>
        </div>
  );
}
